### ISSUE TITLE
Issue with dependency

### ISSUE THREAD

**Issue by vico93** [haykam821/Offline-Player-Teleport#1]
Hi!

Just installed this mod on my server, but when i start it, this error happens:

```
[21:52:09] [main/WARN]: Mod resolution failed
[21:52:09] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE offlineplayerteleport 1.0.0 {depends server_translations_api @ [*]}, ROOT_FORCELOAD_SINGLE offlineplayerteleport 1.0.0]
[21:52:09] [main/INFO]: Reason: [HARD_DEP offlineplayerteleport 1.0.0 {depends server_translations_api @ [*]}]
[21:52:09] [main/INFO]: SERVER environment disabled: [c2me-client-uncapvd, fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, panorama_screens, fabric-models-v0, fabric-rendering-v0, fabric-sound-api-v1, fabric-key-binding-api-v1, fabric-rendering-v1]
[21:52:09] [main/INFO]: Fix: add [add:server_translations_api 1 ([(-?,?)])], remove [], replace []
[21:52:09] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Install server_translations_api, any version.
More details:
         - Mod 'Offline Player Teleport' (offlineplayerteleport) 1.0.0 requires any version of server_translations_api, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
```
Note that the modrinth page doesnt list "server_translations_api" as a dependency.

**Comment by haykam821** [comment]
Server Translations API is not available on Modrinth, but you can find it [here](https://github.com/NucleoidMC/Server-Translations/releases/tag/v2.0.0%2B1.20).

**Comment by syorito-hatsuki** [comment]
> Server Translations API is not available on Modrinth, but you can find it [here](https://github.com/NucleoidMC/Server-Translations/releases/tag/v2.0.0%2B1.20).

Why you didn't include it into your mod🤔

**Comment by haykam821** [comment]
Separating dependencies from the mod allows the mod to support multiple Minecraft versions with one version. If I were to bundle Server Translations API, then I would have to release a new version of this mod every time Server Translations API was updated to support a new Minecraft version. In other words, rather than support Minecraft 1.20 through 1.20.4 (and potentially more versions), I would have to release a version for Minecraft 1.20 and 1.20.1, a version for Minecraft 1.20.2, and a version for Minecraft 1.20.3 and 1.20.4.

If Server Translations API was available on Modrinth, then modpack managers would automatically select the correct version of Server Translations API when downloading this mod. Unfortunately, that is currently not the case, but Server Translations API can still be downloaded from GitHub.
